top_trending_apps/top_trending_apps/urls.py
"""top_trending_apps URL Configuration
"""
from django.contrib import admin
from django.urls import include, path
import twitter_app.urls
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('twitter_app/', include(twitter_app.urls, namespace='twitter_app')),
    path('contact/', views.contact, name='contact'),
    path('admin/', admin.site.urls)
]

top_trending_apps/twitter_app/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'twitter_app/'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    path('', views.index, name='index'),
]

top_trending_apps/twitter_app/models.py
# from django.db import models

# Create your models here.

top_trending_apps/top_trending_apps/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')


def contact(request):
    return render(request, 'contact.html')

top_trending_apps/twitter_app/views.py
from django.shortcuts import render
import requests
from bs4 import BeautifulSoup


def index(request):
    url = 'https://twitter.com/toptweets?lang=en'
    code = requests.get(url)
    plain = code.text
    s = BeautifulSoup(plain, "html.parser")
    tweeter_list = {}
    for name, tweet in zip(s.findAll(attrs={'class': 'fullname show-popup-with'
                                                     '-id u-textTruncate'}),
                           s.findAll(attrs={'class': 'TweetTextSize'})):
        tweeter_list[name.text] = tweet.text
    context = {
        'tweets': tweeter_list
    }
    return render(request, 'index.html', context)

top_trending_apps/top_trending_apps/templates/base.html
<!doctype html>
<meta charset="UTF-8">
<html lang="en">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  margin: 0;
  font-family: Comic Sans MS, cursive, sans-serif;
}

.topnav {
  overflow: hidden;
  background-color: #333;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 14px;
  text-decoration: none;
  font-size: 18px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.topnav a:active {
  background-color: #6BC9D0;
  color: white;
}
</style>
</head>
<body>

<div class="topnav">
  <a class="active" href="{% url 'home' %}">Home</a>
  <a href="{% url 'twitter_app:index' %}">Top Tweets</a>
  <a href="{% url 'contact' %}">Contact</a>
</div>

</body>

{% block body %}
{% endblock %}

top_trending_apps/top_trending_apps/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<style>
.space {
  margin-top: 50px;
}
</style>
<body>
<div class="space">
  <p>If you like my profile, please feel free to contact me via hemantkumar_sk@outlook.com</p>
</div>
</body>

{% endblock %}

top_trending_apps/top_trending_apps/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<body>
<div style="padding-left:16px">
  <h2>Welcome to HK's Django Site</h2>
</div>
</body>
{% endblock %}

top_trending_apps/twitter_app/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div>
    <h2>Top Tweets of the day</h2>
</div>

{% for name, tweet in tweets.items %}
    <div>
        <h3>{{ name }} says: </h3>
        <p>{{ tweet }}</p>
    </div>
{% endfor %}

{% endblock %}